[package]
name = "rolldown_plugin_manifest"
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

[lints]
workspace = true
